### ISSUE TITLE
Bower name confusion

### ISSUE THREAD

**Issue by pirj** [sapo/Ink#427]
Is it 'Ink' or 'InkJS' ? Seems that zurb's ink is using (https://github.com/zurb/ink/blob/master/bower.json) the same name.
Why is it 'InkJS', since it's not JS only?

**Comment by rogeriopvl** [comment]
It's `Ink`.

I'm not sure but `InkJS` was probably created when Ink's css and js where separated repositories (and one imported the other as a git submodule). So this also answers you last question.

Anyway they are both alias of the same repo.

I think that the main confusion about Ink and Zurb's ink (besides that they have the same name, even though sapo/Ink was first) is caused by the fact that Bower package names are case sensitive.

**Comment by pirj** [comment]
Thanks for clarification. I was confused by the fact that bower's online search is showing zurb's ink for both ink and Ink searches, however cli version installs the correct one. I've opened an issue for bower/search (https://github.com/bower/search/issues/62)
