### ISSUE TITLE
cannot open one modal with two links

### ISSUE THREAD

**Issue by DDeme** [sapo/Ink#437]
Ink don't open modal window from more than two links. 

Example code:  testing on quick start with autoload.js  
<code>
   <a href="#" id="modalwin">modalwin</a>
    <a href="#" id="modalwin">modalwin</a>
       
    <div class="ink-shade fade">
        <div id="myModal" class="ink-modal pop-up fade" data-trigger="#contact" data-width="80%" data-height="80%" role="dialog" >
            <div class="modal-body" id="modalContent">
                <button class="pop-up-close ink-dismiss">Close</button>
                <div class="column-group">
                    <div class="all-50 push-center align-left">
                       MY MODAL WINDOW
                    </div>
                </div>
            </div>
        </div>
    </div>
</code>

**Comment by mAiNiNfEcTiOn** [comment]
Hi @DDeme,

In your data-trigger attribute of your modal, try to specify a class instead of an id. E.g.:
```
data-trigger='.yourClass'
```

Then in your links apply that class:
```html
<a class='yourClass' href='#'>link</a>
<a class='yourClass' href='#'>link</a>
```

**Comment by fabiosantoscode** [comment]
Exactly what @mAiNiNfEcTiOn said.

Since IDs are supposed to be unique, using an ID as a selector in Sizzle (which is what we use) will only yield at most one element. So Ink only binds to one of your links.

We agree with this behaviour, since it's very good practise and buggy browsers may have quirks with duplicated IDs as well.

Your example, modified to work:
http://jsbin.com/toruyo/2/edit
