### ISSUE TITLE
Modal background scroll while open

### ISSUE THREAD

**Issue by anvs** [sapo/Ink#457]
It's possible to scroll (body) while a modal is open.
Detected on Safari for iPhone.
Possible solution:

```.ink-modal-open {

overflow: hidden; // already there
position: fixed; // add positioning

}```

**Comment by fabiosantoscode** [comment]
Sorry I took so long to respond.

This is a known issue.

Safari IOS (and most mobile browsers) tend to want to make things scrollable even if they aren't. They have to do this because they have weird heuristics for changing font sizes in different ways, and it might make things scrollable where we put an overflow:hidden and couldn't possibly have prepared for that algorithm. We looked into a lot of things at the time, including what you are suggesting right now, which could make the background not scrollable, but it turns out that the mobile browser is very authoritative about this and nothing works.

In the past we used a pretty nasty hack, which was to save the `scrollTop` of the body, and keep restoring it whenever a `scroll` event occurred. It *worked*, but it was so ugly we just took it off and ended up with the current solution, even though mobile browsers want to let the user scroll behind the modal.

We figured out that using this level of hacks to overthrow current browsers messing with our stuff was counter-productive and goes against what we try to do with Ink, which is do things the most simple and unobstrusive way possible, and weighed that against the cost of a small glitch (being able to scroll the content behind the modal).

If some CSS property or HTML attribute comes up to let us tell the browser to not mess this up, I hope we can be the first to use it. Until then, we need to learn to live with this.
