### ISSUE TITLE
Prevent drawer from closing

### ISSUE THREAD

**Issue by niknetniko** [sapo/Ink#463]
Hi!

First of, thanks for the awesome framework.

I have an issue and I'm not sure how to proceed. The js-fiddle: http://jsfiddle.net/uhwzsjxj/1/

The problem is that I have a drawer with in that drawer a menu, with a submenu. On mobile, clicking the parent of the submenu closes the drawer, which makes it so that you cannot click on the submenu's (happens on desktop as well, but less of an issue, since you can hover over it).

My questions is how would I prevent the drawer from closing in case I click the parent of a submenu?

**Comment by gnpfonseca** [comment]
Hi,

we're glad that you're enjoying the framework. :)

Regarding the issue of making the submenu work with a toggle behaviour, you can use this code http://jsfiddle.net/uhwzsjxj/5/

However, when you click an anchor within the drawer menu, the expected behavior is the drawer to close 
and navigating away to whatever url you place on your href. So, i would recommend using a button instead of an anchor as a trigger for the submenu.

PS:  please have in mind that our menus and submenus are not made to work like this. So, an additional selector had to be added to the CSS to make it work.

Cheers!

**Comment by niknetniko** [comment]
Thank you very much! Your solution using the toggle works a charm and is perfect :)
